Lt 3011 product complexity
lykkecloud/MarginTrading.AccountsManagement pull request #123
Opened 2021-02-17 18:42 UTC by avolkov-dev

2021-03-05 10:17 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/ComplexityWarningRepository.cs
> +                throw new InvalidOperationException($"Optimistic concurrency happened while insert of product complexity state for account {accountId}", e);
So it means the entity has already been inserted into database. Do we need to taise an exception or returning the entity would be better?

2021-03-09 09:32 UTC, avolkov-dev commented on src/MarginTrading.AccountsManagement/InternalModels/ComplexityWarningState.cs
> +            if (!ConfirmedOrders.ContainsKey(orderId))
i guess, it's possible. that's why we have optimistic concurrency in place.

2021-03-09 09:33 UTC, avolkov-dev commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/ComplexityWarningRepository.cs
> +                throw new InvalidOperationException($"Optimistic concurrency happened while insert of product complexity state for account {accountId}", e);
Probably returning the entity would be better (less error prone in logs). will change the implementation

2021-03-10 05:47 UTC, andrey-anokhin requested changes

2021-03-10 05:47 UTC, andrey-anokhin commented on src/MarginTrading.AccountsManagement/Workflow/ProductComplexity/OrderHistoryListener.cs
> +                .Subscribe(@event => this.DecorateAndHandle(() => this.Handle(@event)))
We should not use DecorateAndHandle (this approach was used a long time ago by another team) because, in case of any error in the Handle method (for example, DB is unavailable or timed out), we will log an error and just skip the message, which may lead to wrong account state. The default approach for such subscribers should be several retries + poison queue (see https://github.com/lykkecloud/MarginTrading.BrokerBase/blob/master/src/MarginTrading.BrokerBase/BrokerApplicationBase.cs#L91), ideally with the possibility to move messages from the poison queue back (see https://github.com/lykkecloud/MarginTrading.BrokerBase/blob/master/src/MarginTrading.BrokerBase/Controllers/PoisonController.cs).

2021-03-10 05:47 UTC, andrey-anokhin commented on src/MarginTrading.AccountsManagement/Workflow/ProductComplexity/OrderHistoryListener.cs
> +            if (!await _featureManager.IsEnabledAsync(BrokerFeature.ProductComplexityWarning))
Maybe if the feature is disabled we don't need to subscribe at all?

2021-03-10 05:47 UTC, andrey-anokhin commented on src/MarginTrading.AccountsManagement/Workflow/ProductComplexity/OrderHistoryListener.cs
> +            if (_settings.ComplexityWarningsCount <= 0)
I think it makes sense to make such validations at the start and just do not start at all in case of the wrong configuration.

2021-03-10 05:47 UTC, andrey-anokhin commented on src/MarginTrading.AccountsManagement/Workflow/ProductComplexity/ServiceCollectionExtensions.cs
> +                    new DefaultErrorHandlingStrategy(
We should change at least to ResilientErrorHandlingStrategy

2021-03-10 09:29 UTC, andrey-anokhin approved these changes

2021-03-10 09:29 UTC, merged